import Head from 'next/head'
import Button from './_button'

export default function Home() {
  return (
    <>
      <Head>
        <title>Clase 09 next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Hello Words!!!
        <br></br>
        <h1> Ejercicio Nº9</h1>
        <br></br>


      </main>
      <Button></Button>
    </>
  )
}
